CREATE TABLE IF NOT EXISTS public.study_plans (
  id SERIAL PRIMARY KEY,
  exam_id INTEGER REFERENCES public.exams(id) ON DELETE CASCADE,
  nodes JSONB NOT NULL,
  edges JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 